/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SshRouteImport } from './routes/ssh'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RepoRouteImport } from './routes/repo'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as SettingsSshRouteImport } from './routes/settings.ssh'
import { Route as CreateAstroRouteImport } from './routes/create.astro'

const SshRoute = SshRouteImport.update({
  id: '/ssh',
  path: '/ssh',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRoute = RepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const SettingsSshRoute = SettingsSshRouteImport.update({
  id: '/ssh',
  path: '/ssh',
  getParentRoute: () => SettingsRoute,
} as any)
const CreateAstroRoute = CreateAstroRouteImport.update({
  id: '/astro',
  path: '/astro',
  getParentRoute: () => CreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/overview': typeof OverviewRoute
  '/repo': typeof RepoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ssh': typeof SshRoute
  '/create/astro': typeof CreateAstroRoute
  '/settings/ssh': typeof SettingsSshRoute
  '/create/': typeof CreateIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/repo': typeof RepoRoute
  '/ssh': typeof SshRoute
  '/create/astro': typeof CreateAstroRoute
  '/settings/ssh': typeof SettingsSshRoute
  '/create': typeof CreateIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/overview': typeof OverviewRoute
  '/repo': typeof RepoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ssh': typeof SshRoute
  '/create/astro': typeof CreateAstroRoute
  '/settings/ssh': typeof SettingsSshRoute
  '/create/': typeof CreateIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/overview'
    | '/repo'
    | '/settings'
    | '/ssh'
    | '/create/astro'
    | '/settings/ssh'
    | '/create/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/overview'
    | '/repo'
    | '/ssh'
    | '/create/astro'
    | '/settings/ssh'
    | '/create'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/overview'
    | '/repo'
    | '/settings'
    | '/ssh'
    | '/create/astro'
    | '/settings/ssh'
    | '/create/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRouteWithChildren
  OverviewRoute: typeof OverviewRoute
  RepoRoute: typeof RepoRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SshRoute: typeof SshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ssh': {
      id: '/ssh'
      path: '/ssh'
      fullPath: '/ssh'
      preLoaderRoute: typeof SshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo': {
      id: '/repo'
      path: '/repo'
      fullPath: '/repo'
      preLoaderRoute: typeof RepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/settings/ssh': {
      id: '/settings/ssh'
      path: '/ssh'
      fullPath: '/settings/ssh'
      preLoaderRoute: typeof SettingsSshRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/create/astro': {
      id: '/create/astro'
      path: '/astro'
      fullPath: '/create/astro'
      preLoaderRoute: typeof CreateAstroRouteImport
      parentRoute: typeof CreateRoute
    }
  }
}

interface CreateRouteChildren {
  CreateAstroRoute: typeof CreateAstroRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateAstroRoute: CreateAstroRoute,
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

interface SettingsRouteChildren {
  SettingsSshRoute: typeof SettingsSshRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSshRoute: SettingsSshRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRouteWithChildren,
  OverviewRoute: OverviewRoute,
  RepoRoute: RepoRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SshRoute: SshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
