/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SshRouteImport } from './routes/ssh'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RepoRouteImport } from './routes/repo'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSshRouteImport } from './routes/settings.ssh'

const SshRoute = SshRouteImport.update({
  id: '/ssh',
  path: '/ssh',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRoute = RepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSshRoute = SettingsSshRouteImport.update({
  id: '/ssh',
  path: '/ssh',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/repo': typeof RepoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ssh': typeof SshRoute
  '/settings/ssh': typeof SettingsSshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/repo': typeof RepoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ssh': typeof SshRoute
  '/settings/ssh': typeof SettingsSshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/repo': typeof RepoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/ssh': typeof SshRoute
  '/settings/ssh': typeof SettingsSshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/overview'
    | '/repo'
    | '/settings'
    | '/ssh'
    | '/settings/ssh'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/overview' | '/repo' | '/settings' | '/ssh' | '/settings/ssh'
  id:
    | '__root__'
    | '/'
    | '/overview'
    | '/repo'
    | '/settings'
    | '/ssh'
    | '/settings/ssh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverviewRoute: typeof OverviewRoute
  RepoRoute: typeof RepoRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SshRoute: typeof SshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ssh': {
      id: '/ssh'
      path: '/ssh'
      fullPath: '/ssh'
      preLoaderRoute: typeof SshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo': {
      id: '/repo'
      path: '/repo'
      fullPath: '/repo'
      preLoaderRoute: typeof RepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ssh': {
      id: '/settings/ssh'
      path: '/ssh'
      fullPath: '/settings/ssh'
      preLoaderRoute: typeof SettingsSshRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsSshRoute: typeof SettingsSshRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSshRoute: SettingsSshRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverviewRoute: OverviewRoute,
  RepoRoute: RepoRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SshRoute: SshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
